#!/bin/sh
#
# 2014-08-26, Created by H Fuchs <code@hfuchs.net>
# This wrapper for usbmount.real gets called as a udev hook and simply
# runs a usbmount.real process for every udev usb device event in the
# background -- as per udev specifications.  They don't like it when
# udev hooks do heavy lifting.

/usr/share/usbmount/usbmount.real $1 &

